---
name: "Cache Node modules"
description: "Cache Node modules"

runs:
  using: "composite"
  steps:
    - name: Restore node modules from cache
      id: cache-nodemodules
      uses: actions/cache/restore@v3
      with:
        # cache whole node_modules instead of ./npm, means `npm ci` will be skipped if cache hit, https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/
        path: ./node_modules
        key: ${{ runner.os }}-nodemodules-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nodemodules-

    - name: Install dependencies
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --ignore-scripts
