name: Build and Test

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    env:
      DEPLOYMENTS: MAINNET,TESTNET
      MAINNET_BRIDGE_ADDRESS: 0xBa5E35E26Ae59c7aea6F029B68c6460De2d13eB6
      MAINNET_FLOW_RATED_TOKENS: 0x0000000000000000000000000000000000000Eee,0xF57e7e7C23978C3cAEC3C3548E3D615c346e79fF,0xdAC17F958D2ee523a2206206994597C13D831ec7,0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599,0xccC8cb5229B0ac8069C51fd58367Fd1e622aFD97,0x9AB7bb7FdC60f4357ECFef43986818A2A3569c62
      TESTNET_BRIDGE_ADDRESS: 0x0D3C59c779Fd552C27b23F723E80246c840100F5
      TESTNET_FLOW_RATED_TOKENS: 0x0000000000000000000000000000000000000Eee,0xe2629e08f4125d14e446660028bd98ee60ee69f2
    strategy:
      fail-fast: true
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run unit and integration tests
        run: |
          forge test --no-match-path "test/fork/**" -vvv
        id: unit_integration_test

      - name: Run Fork Tests
        run: |
          forge test --match-path "test/fork/**" -vvvvv
        id: fork_test
