name: Build and Test

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    env:
      DEPLOYMENTS: ${{ vars.DEPLOYMENTS }}
      MAINNET_BRIDGE_ADDRESS: ${{ vars.MAINNET_BRIDGE_ADDRESS }}
      MAINNET_FLOW_RATED_TOKENS: ${{ vars.MAINNET_FLOW_RATED_TOKENS }}
      TESTNET_BRIDGE_ADDRESS: ${{ vars.TESTNET_BRIDGE_ADDRESS }}
      TESTNET_FLOW_RATED_TOKENS: ${{ vars.TESTNET_FLOW_RATED_TOKENS }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
    strategy:
      fail-fast: true
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run unit and integration tests
        run: |
          forge test --no-match-path "test/fork/**" -vvv
        id: unit_integration_test

      - name: Run Fork Tests
        run: |
          forge test --match-path "test/fork/**" -vvvvv
        id: fork_test
